// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/quran/index.mdx?collection=docs&hash=1767833336068"
import * as docs_8 from "../content/docs/quran/data-format.mdx?collection=docs&hash=1767833336068"
import * as docs_7 from "../content/docs/quran/api.mdx?collection=docs&hash=1767833336068"
import * as docs_6 from "../content/docs/qibla/index.mdx?collection=docs&hash=1767833336068"
import * as docs_5 from "../content/docs/qibla/api.mdx?collection=docs&hash=1767833336068"
import * as docs_4 from "../content/docs/prayer-times/quick-start.mdx?collection=docs&hash=1767833336068"
import * as docs_3 from "../content/docs/prayer-times/index.mdx?collection=docs&hash=1767833336068"
import * as docs_2 from "../content/docs/prayer-times/calculation-methods.mdx?collection=docs&hash=1767833336068"
import * as docs_1 from "../content/docs/prayer-times/api.mdx?collection=docs&hash=1767833336068"
import * as docs_0 from "../content/docs/getting-started.mdx?collection=docs&hash=1767833336068"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"getting-started.mdx","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/getting-started.mdx"}, data: docs_0 }, { info: {"path":"prayer-times/api.mdx","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/prayer-times/api.mdx"}, data: docs_1 }, { info: {"path":"prayer-times/calculation-methods.mdx","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/prayer-times/calculation-methods.mdx"}, data: docs_2 }, { info: {"path":"prayer-times/index.mdx","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/prayer-times/index.mdx"}, data: docs_3 }, { info: {"path":"prayer-times/quick-start.mdx","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/prayer-times/quick-start.mdx"}, data: docs_4 }, { info: {"path":"qibla/api.mdx","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/qibla/api.mdx"}, data: docs_5 }, { info: {"path":"qibla/index.mdx","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/qibla/index.mdx"}, data: docs_6 }, { info: {"path":"quran/api.mdx","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/quran/api.mdx"}, data: docs_7 }, { info: {"path":"quran/data-format.mdx","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/quran/data-format.mdx"}, data: docs_8 }, { info: {"path":"quran/index.mdx","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/quran/index.mdx"}, data: docs_9 }], [{"info":{"path":"meta.json","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/meta.json"},"data":{"title":"Documentation","pages":["getting-started","prayer-times","qibla","quran"]}}, {"info":{"path":"prayer-times/meta.json","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/prayer-times/meta.json"},"data":{"title":"Prayer Times","pages":["index","quick-start","calculation-methods","api"]}}, {"info":{"path":"qibla/meta.json","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/qibla/meta.json"},"data":{"title":"Qibla Direction","pages":["index","api"]}}, {"info":{"path":"quran/meta.json","absolutePath":"/Users/asadkomi/Documents/Personal/islam-kit/apps/docs/content/docs/quran/meta.json"},"data":{"title":"Quran","pages":["index","data-format","api"]}}])