name: Bug Report
description: Report a bug in an Islam Kit package
labels: ['bug']
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - '@islam-kit/prayer-times'
        - '@islam-kit/qibla'
        - '@islam-kit/quran'
        - 'Documentation'
        - 'Other'
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import '...'
        2. Call '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code example
      description: Minimal code that reproduces the issue
      render: typescript

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Node.js
        - Browser
        - React
        - React Native / Expo
        - Next.js
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: e.g., 20.10.0
